[package]
name = "sum_merkle_tree"
version = "0.1.0"
authors = ["Cryptoeconomics Lab <info@cryptoeconomicslab.com>"]
edition = "2018"

[dependencies]
rust-crypto = {git="https://github.com/debris/rust-crypto.git", branch="android"}
bytes = "0.4.12"
byteorder = "1.3.1"
